development:
  adapter: mysql2
  encoding: utf8
  database: droid_development
  username: root
  host: mysql-droid-market
  password:

test: &test
  adapter: mysql2
  encoding: utf8
  database: droid_test
  username: root
  host: mysql-droid-market
  password:

cucumber:
  <<: *test